version: 2
updates:
  - package-ecosystem: "npm" # Update this based on the stack
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
       dependencies:
          patterns:
            - "*"
